
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Inicio_App = 2;
  public static final int PuntoComa = 33;
  public static final int Dec = 11;
  public static final int Alto = 24;
  public static final int Real = 14;
  public static final int Potencia = 32;
  public static final int Mas = 28;
  public static final int Menor = 26;
  public static final int llaveCierre = 35;
  public static final int Ingresa = 8;
  public static final int Mayor = 27;
  public static final int ParentesisCierre = 37;
  public static final int Car = 17;
  public static final int Text = 9;
  public static final int Division = 31;
  public static final int Avanza = 23;
  public static final int EOF = 0;
  public static final int Durante = 4;
  public static final int error = 1;
  public static final int Funcion = 20;
  public static final int Repite = 5;
  public static final int Publica = 12;
  public static final int Inc = 10;
  public static final int ERROR = 40;
  public static final int Tarea = 3;
  public static final int Girar_De = 22;
  public static final int RealExt = 15;
  public static final int Imprime = 7;
  public static final int Identificador = 38;
  public static final int Girar_Iz = 21;
  public static final int Resta = 29;
  public static final int Vibrar = 18;
  public static final int Bool = 16;
  public static final int Multiplicacion = 30;
  public static final int Ent = 13;
  public static final int Y_si = 6;
  public static final int Numero = 39;
  public static final int ParentesisApertura = 36;
  public static final int llaveApertura = 34;
  public static final int Igual = 25;
  public static final int Ir = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Inicio_App",
  "Tarea",
  "Durante",
  "Repite",
  "Y_si",
  "Imprime",
  "Ingresa",
  "Text",
  "Inc",
  "Dec",
  "Publica",
  "Ent",
  "Real",
  "RealExt",
  "Bool",
  "Car",
  "Vibrar",
  "Ir",
  "Funcion",
  "Girar_Iz",
  "Girar_De",
  "Avanza",
  "Alto",
  "Igual",
  "Menor",
  "Mayor",
  "Mas",
  "Resta",
  "Multiplicacion",
  "Division",
  "Potencia",
  "PuntoComa",
  "llaveApertura",
  "llaveCierre",
  "ParentesisApertura",
  "ParentesisCierre",
  "Identificador",
  "Numero",
  "ERROR"
  };
}

