/* The following code was generated by JFlex 1.7.0 */

package codigo;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/proyectosNeatBeans/JVirtualLocal/src/codigo/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\45\1\46\1\46\1\45\22\0\1\3\7\0\1\61"+
    "\1\62\1\54\1\52\1\3\1\53\1\0\1\44\12\2\1\0\1\56"+
    "\1\50\1\47\1\51\2\0\1\12\1\35\1\36\1\20\1\34\1\40"+
    "\1\41\1\1\1\4\6\1\1\31\1\1\1\23\1\1\1\14\1\1"+
    "\1\37\2\1\1\24\1\1\3\0\1\55\1\11\1\0\1\15\1\32"+
    "\1\7\1\1\1\17\1\1\1\27\1\1\1\6\2\1\1\33\1\26"+
    "\1\5\1\10\1\13\1\1\1\16\1\25\1\22\1\21\1\43\1\1"+
    "\1\30\1\1\1\42\1\57\1\0\1\60\7\0\1\46\u1fa2\0\1\46"+
    "\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\15\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\2\1\22\20\2\1\4\1\0"+
    "\1\2\1\23\6\2\1\24\5\2\1\25\1\2\1\26"+
    "\3\2\1\0\3\2\1\27\2\2\1\30\2\2\1\31"+
    "\1\32\1\2\1\33\3\2\1\3\4\2\1\34\12\2"+
    "\1\35\1\2\1\36\2\2\1\37\3\2\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\3\2\1\46\1\47\1\2"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd"+
    "\0\u0330\0\u0363\0\u0396\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\u03c9\0\63\0\u03fc"+
    "\0\146\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9"+
    "\0\u072c\0\u075f\0\u0792\0\u07c5\0\146\0\u07f8\0\u082b\0\u085e"+
    "\0\u0891\0\u08c4\0\u08f7\0\146\0\u092a\0\u095d\0\u0990\0\u09c3"+
    "\0\u09f6\0\146\0\u0a29\0\146\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5"+
    "\0\u0b28\0\u0b5b\0\u0b8e\0\146\0\u0bc1\0\u0bf4\0\146\0\u0c27"+
    "\0\u0c5a\0\u0c8d\0\146\0\u0cc0\0\146\0\u0cf3\0\u0d26\0\u0d59"+
    "\0\63\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\146\0\u0e58\0\u0e8b"+
    "\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023"+
    "\0\146\0\u1056\0\146\0\u1089\0\u10bc\0\146\0\u10ef\0\u1122"+
    "\0\u1155\0\146\0\146\0\146\0\146\0\146\0\146\0\u1188"+
    "\0\u11bb\0\u11ee\0\146\0\146\0\u1221\0\146";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\5\3\1\7\1\3"+
    "\1\10\3\3\1\11\2\3\1\12\1\13\4\3\1\14"+
    "\2\3\1\15\1\16\1\17\1\20\1\21\1\22\2\3"+
    "\1\23\1\5\1\0\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\64\0"+
    "\2\3\1\0\40\3\21\0\1\4\63\0\1\5\41\0"+
    "\1\5\16\0\2\3\1\0\1\3\1\40\10\3\1\41"+
    "\7\3\1\42\15\3\20\0\2\3\1\0\27\3\1\43"+
    "\7\3\1\44\20\0\2\3\1\0\11\3\1\45\1\3"+
    "\1\46\24\3\20\0\2\3\1\0\13\3\1\47\1\3"+
    "\1\50\22\3\20\0\2\3\1\0\13\3\1\51\24\3"+
    "\20\0\2\3\1\0\5\3\1\52\32\3\20\0\2\3"+
    "\1\0\15\3\1\53\22\3\20\0\2\3\1\0\1\3"+
    "\1\54\36\3\20\0\2\3\1\0\4\3\1\55\33\3"+
    "\20\0\2\3\1\0\11\3\1\56\26\3\20\0\2\3"+
    "\1\0\2\3\1\57\35\3\20\0\2\3\1\0\15\3"+
    "\1\60\22\3\20\0\2\3\1\0\2\3\1\61\35\3"+
    "\63\0\1\62\71\0\1\63\10\0\2\3\1\0\2\3"+
    "\1\64\1\65\17\3\1\66\14\3\20\0\2\3\1\0"+
    "\7\3\1\67\30\3\20\0\2\3\1\0\16\3\1\70"+
    "\21\3\20\0\2\3\1\0\11\3\1\71\26\3\20\0"+
    "\2\3\1\0\12\3\1\72\25\3\20\0\2\3\1\0"+
    "\24\3\1\73\13\3\20\0\2\3\1\0\3\3\1\74"+
    "\34\3\20\0\2\3\1\0\12\3\1\75\25\3\20\0"+
    "\2\3\1\0\7\3\1\76\1\3\1\77\26\3\20\0"+
    "\2\3\1\0\21\3\1\100\16\3\20\0\2\3\1\0"+
    "\26\3\1\101\11\3\20\0\2\3\1\0\16\3\1\102"+
    "\21\3\20\0\2\3\1\0\4\3\1\103\33\3\20\0"+
    "\2\3\1\0\12\3\1\104\25\3\20\0\2\3\1\0"+
    "\26\3\1\105\11\3\20\0\2\3\1\0\1\3\1\106"+
    "\36\3\20\0\2\3\1\0\12\3\1\107\25\3\17\0"+
    "\45\62\2\0\14\62\2\0\1\110\61\0\2\3\1\0"+
    "\3\3\1\111\34\3\20\0\2\3\1\0\12\3\1\112"+
    "\25\3\20\0\2\3\1\0\12\3\1\113\25\3\20\0"+
    "\2\3\1\0\4\3\1\114\33\3\20\0\2\3\1\0"+
    "\1\3\1\115\36\3\20\0\2\3\1\0\13\3\1\116"+
    "\24\3\20\0\2\3\1\0\16\3\1\117\21\3\20\0"+
    "\2\3\1\0\11\3\1\120\26\3\20\0\2\3\1\0"+
    "\2\3\1\121\35\3\20\0\2\3\1\0\27\3\1\122"+
    "\10\3\20\0\2\3\1\0\2\3\1\123\35\3\20\0"+
    "\2\3\1\0\27\3\1\124\10\3\20\0\2\3\1\0"+
    "\27\3\1\125\10\3\20\0\2\3\1\0\12\3\1\126"+
    "\25\3\20\0\2\3\1\0\3\3\1\127\34\3\20\0"+
    "\2\3\1\0\11\3\1\130\26\3\21\0\1\110\57\0"+
    "\1\131\1\0\2\3\1\0\2\3\1\132\35\3\20\0"+
    "\2\3\1\0\13\3\1\133\24\3\20\0\2\3\1\0"+
    "\2\3\1\134\35\3\20\0\2\3\1\0\36\3\1\135"+
    "\1\3\20\0\2\3\1\0\11\3\1\136\26\3\20\0"+
    "\2\3\1\0\1\3\1\137\36\3\20\0\2\3\1\0"+
    "\16\3\1\140\21\3\20\0\2\3\1\0\30\3\1\141"+
    "\7\3\20\0\2\3\1\0\2\3\1\142\35\3\20\0"+
    "\2\3\1\0\11\3\1\143\26\3\20\0\2\3\1\0"+
    "\2\3\1\144\35\3\20\0\2\3\1\0\12\3\1\145"+
    "\25\3\20\0\2\3\1\0\4\3\1\146\33\3\20\0"+
    "\2\3\1\0\21\3\1\147\16\3\20\0\2\3\1\0"+
    "\22\3\1\150\15\3\20\0\2\3\1\0\11\3\1\151"+
    "\26\3\20\0\2\3\1\0\16\3\1\152\21\3\20\0"+
    "\2\3\1\0\13\3\1\153\24\3\20\0\2\3\1\0"+
    "\24\3\1\154\13\3\20\0\2\3\1\0\3\3\1\155"+
    "\34\3\20\0\2\3\1\0\12\3\1\156\25\3\20\0"+
    "\2\3\1\0\4\3\1\157\33\3\20\0\2\3\1\0"+
    "\5\3\1\160\32\3\20\0\2\3\1\0\5\3\1\161"+
    "\32\3\20\0\2\3\1\0\11\3\1\162\26\3\20\0"+
    "\2\3\1\0\13\3\1\163\24\3\20\0\2\3\1\0"+
    "\13\3\1\164\24\3\20\0\2\3\1\0\16\3\1\165"+
    "\21\3\20\0\2\3\1\0\11\3\1\166\26\3\20\0"+
    "\2\3\1\0\1\3\1\167\36\3\20\0\2\3\1\0"+
    "\1\170\13\3\1\171\23\3\20\0\2\3\1\0\6\3"+
    "\1\172\31\3\20\0\2\3\1\0\36\3\1\173\1\3"+
    "\20\0\2\3\1\0\13\3\1\174\24\3\20\0\2\3"+
    "\1\0\7\3\1\175\30\3\20\0\2\3\1\0\7\3"+
    "\1\176\30\3\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4692];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\21\1\12\11\1\1\1\11\23\1\1\0"+
    "\24\1\1\0\20\1\1\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol (int type, Object value){
        return new Symbol (type, yyline, yycolumn, value);       
    }
    
    private Symbol symbol (int type){
        return new Symbol (type, yyline, yycolumn);       
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol (sym.ERROR, yychar, yyline, yytext());
            } 
            // fall through
          case 41: break;
          case 2: 
            { return new Symbol (sym.Identificador, yychar, yyline, yytext());
            } 
            // fall through
          case 42: break;
          case 3: 
            { return new Symbol (sym.Numero, yychar, yyline, yytext());
            } 
            // fall through
          case 43: break;
          case 4: 
            { /*Ignore*/
            } 
            // fall through
          case 44: break;
          case 5: 
            { return new Symbol (sym.Division, yychar, yyline, yytext());
            } 
            // fall through
          case 45: break;
          case 6: 
            { return new Symbol (sym.Igual, yychar, yyline, yytext());
            } 
            // fall through
          case 46: break;
          case 7: 
            { return new Symbol (sym.Menor, yychar, yyline, yytext());
            } 
            // fall through
          case 47: break;
          case 8: 
            { return new Symbol (sym.Mayor, yychar, yyline, yytext());
            } 
            // fall through
          case 48: break;
          case 9: 
            { return new Symbol (sym.Mas, yychar, yyline, yytext());
            } 
            // fall through
          case 49: break;
          case 10: 
            { return new Symbol (sym.Resta, yychar, yyline, yytext());
            } 
            // fall through
          case 50: break;
          case 11: 
            { return new Symbol (sym.Multiplicacion, yychar, yyline, yytext());
            } 
            // fall through
          case 51: break;
          case 12: 
            { return new Symbol (sym.Potencia, yychar, yyline, yytext());
            } 
            // fall through
          case 52: break;
          case 13: 
            { return new Symbol (sym.PuntoComa, yychar, yyline, yytext());
            } 
            // fall through
          case 53: break;
          case 14: 
            { return new Symbol (sym.llaveApertura, yychar, yyline, yytext());
            } 
            // fall through
          case 54: break;
          case 15: 
            { return new Symbol (sym.llaveCierre, yychar, yyline, yytext());
            } 
            // fall through
          case 55: break;
          case 16: 
            { return new Symbol (sym.ParentesisApertura, yychar, yyline, yytext());
            } 
            // fall through
          case 56: break;
          case 17: 
            { return new Symbol (sym.ParentesisCierre, yychar, yyline, yytext());
            } 
            // fall through
          case 57: break;
          case 18: 
            { return new Symbol (sym.Ir, yychar, yyline, yytext());
            } 
            // fall through
          case 58: break;
          case 19: 
            { return new Symbol (sym.Inc, yychar, yyline, yytext());
            } 
            // fall through
          case 59: break;
          case 20: 
            { return new Symbol (sym.Dec, yychar, yyline, yytext());
            } 
            // fall through
          case 60: break;
          case 21: 
            { return new Symbol (sym.Ent, yychar, yyline, yytext());
            } 
            // fall through
          case 61: break;
          case 22: 
            { return new Symbol (sym.Car, yychar, yyline, yytext());
            } 
            // fall through
          case 62: break;
          case 23: 
            { return new Symbol (sym.Alto, yychar, yyline, yytext());
            } 
            // fall through
          case 63: break;
          case 24: 
            { return new Symbol (sym.Text, yychar, yyline, yytext());
            } 
            // fall through
          case 64: break;
          case 25: 
            { return new Symbol (sym.Real, yychar, yyline, yytext());
            } 
            // fall through
          case 65: break;
          case 26: 
            { return new Symbol (sym.Y_si, yychar, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 27: 
            { return new Symbol (sym.Bool, yychar, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 28: 
            { return new Symbol (sym.Tarea, yychar, yyline, yytext());
            } 
            // fall through
          case 68: break;
          case 29: 
            { return new Symbol (sym.Avanza, yychar, yyline, yytext());
            } 
            // fall through
          case 69: break;
          case 30: 
            { return new Symbol (sym.Repite, yychar, yyline, yytext());
            } 
            // fall through
          case 70: break;
          case 31: 
            { return new Symbol (sym.Vibrar, yychar, yyline, yytext());
            } 
            // fall through
          case 71: break;
          case 32: 
            { return new Symbol (sym.Ingresa, yychar, yyline, yytext());
            } 
            // fall through
          case 72: break;
          case 33: 
            { return new Symbol (sym.Imprime, yychar, yyline, yytext());
            } 
            // fall through
          case 73: break;
          case 34: 
            { return new Symbol (sym.Durante, yychar, yyline, yytext());
            } 
            // fall through
          case 74: break;
          case 35: 
            { return new Symbol (sym.RealExt, yychar, yyline, yytext());
            } 
            // fall through
          case 75: break;
          case 36: 
            { return new Symbol (sym.Publica, yychar, yyline, yytext());
            } 
            // fall through
          case 76: break;
          case 37: 
            { return new Symbol (sym.Funcion, yychar, yyline, yytext());
            } 
            // fall through
          case 77: break;
          case 38: 
            { return new Symbol (sym.Girar_Iz, yychar, yyline, yytext());
            } 
            // fall through
          case 78: break;
          case 39: 
            { return new Symbol (sym.Girar_De, yychar, yyline, yytext());
            } 
            // fall through
          case 79: break;
          case 40: 
            { return new Symbol (sym.Inicio_App, yychar, yyline,yytext());
            } 
            // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
