/* The following code was generated by JFlex 1.7.0 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/dokxo/Documents/NetBeansProjects/JVirtual/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\45\1\47\1\47\1\46\22\0\1\3\7\0\1\62"+
    "\1\63\1\55\1\53\1\3\1\54\1\0\1\44\12\2\1\0\1\57"+
    "\1\51\1\50\1\52\2\0\1\12\1\35\1\36\1\20\1\34\1\40"+
    "\1\41\1\1\1\4\6\1\1\31\1\1\1\23\1\1\1\14\1\1"+
    "\1\37\2\1\1\24\1\1\3\0\1\56\1\11\1\0\1\15\1\32"+
    "\1\7\1\1\1\17\1\1\1\27\1\1\1\6\2\1\1\33\1\26"+
    "\1\5\1\10\1\13\1\1\1\16\1\25\1\22\1\21\1\43\1\1"+
    "\1\30\1\1\1\42\1\60\1\0\1\61\7\0\1\47\u1fa2\0\1\47"+
    "\1\47\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\15\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\2\1\23\20\2\1\4"+
    "\1\0\1\2\1\24\6\2\1\25\5\2\1\26\1\2"+
    "\1\27\3\2\1\0\3\2\1\30\2\2\1\31\2\2"+
    "\1\32\1\33\1\2\1\34\3\2\1\3\4\2\1\35"+
    "\12\2\1\36\1\2\1\37\2\2\1\40\3\2\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\3\2\1\47\1\50"+
    "\1\2\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c"+
    "\0\u0340\0\u0374\0\u03a8\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u03dc\0\64"+
    "\0\u0410\0\150\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548"+
    "\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8"+
    "\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\150\0\u0820\0\u0854"+
    "\0\u0888\0\u08bc\0\u08f0\0\u0924\0\150\0\u0958\0\u098c\0\u09c0"+
    "\0\u09f4\0\u0a28\0\150\0\u0a5c\0\150\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\150\0\u0bfc\0\u0c30\0\150"+
    "\0\u0c64\0\u0c98\0\u0ccc\0\150\0\u0d00\0\150\0\u0d34\0\u0d68"+
    "\0\u0d9c\0\64\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\150\0\u0ea0"+
    "\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040"+
    "\0\u1074\0\150\0\u10a8\0\150\0\u10dc\0\u1110\0\150\0\u1144"+
    "\0\u1178\0\u11ac\0\150\0\150\0\150\0\150\0\150\0\150"+
    "\0\u11e0\0\u1214\0\u1248\0\150\0\150\0\u127c\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\5\3\1\7\1\3"+
    "\1\10\3\3\1\11\2\3\1\12\1\13\4\3\1\14"+
    "\2\3\1\15\1\16\1\17\1\20\1\21\1\22\2\3"+
    "\1\23\1\24\1\5\1\0\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\65\0\2\3\1\0\40\3\22\0\1\4\64\0\1\5"+
    "\42\0\1\5\16\0\2\3\1\0\1\3\1\41\10\3"+
    "\1\42\7\3\1\43\15\3\21\0\2\3\1\0\27\3"+
    "\1\44\7\3\1\45\21\0\2\3\1\0\11\3\1\46"+
    "\1\3\1\47\24\3\21\0\2\3\1\0\13\3\1\50"+
    "\1\3\1\51\22\3\21\0\2\3\1\0\13\3\1\52"+
    "\24\3\21\0\2\3\1\0\5\3\1\53\32\3\21\0"+
    "\2\3\1\0\15\3\1\54\22\3\21\0\2\3\1\0"+
    "\1\3\1\55\36\3\21\0\2\3\1\0\4\3\1\56"+
    "\33\3\21\0\2\3\1\0\11\3\1\57\26\3\21\0"+
    "\2\3\1\0\2\3\1\60\35\3\21\0\2\3\1\0"+
    "\15\3\1\61\22\3\21\0\2\3\1\0\2\3\1\62"+
    "\35\3\64\0\1\63\73\0\1\64\10\0\2\3\1\0"+
    "\2\3\1\65\1\66\17\3\1\67\14\3\21\0\2\3"+
    "\1\0\7\3\1\70\30\3\21\0\2\3\1\0\16\3"+
    "\1\71\21\3\21\0\2\3\1\0\11\3\1\72\26\3"+
    "\21\0\2\3\1\0\12\3\1\73\25\3\21\0\2\3"+
    "\1\0\24\3\1\74\13\3\21\0\2\3\1\0\3\3"+
    "\1\75\34\3\21\0\2\3\1\0\12\3\1\76\25\3"+
    "\21\0\2\3\1\0\7\3\1\77\1\3\1\100\26\3"+
    "\21\0\2\3\1\0\21\3\1\101\16\3\21\0\2\3"+
    "\1\0\26\3\1\102\11\3\21\0\2\3\1\0\16\3"+
    "\1\103\21\3\21\0\2\3\1\0\4\3\1\104\33\3"+
    "\21\0\2\3\1\0\12\3\1\105\25\3\21\0\2\3"+
    "\1\0\26\3\1\106\11\3\21\0\2\3\1\0\1\3"+
    "\1\107\36\3\21\0\2\3\1\0\12\3\1\110\25\3"+
    "\20\0\45\63\3\0\14\63\2\0\1\111\62\0\2\3"+
    "\1\0\3\3\1\112\34\3\21\0\2\3\1\0\12\3"+
    "\1\113\25\3\21\0\2\3\1\0\12\3\1\114\25\3"+
    "\21\0\2\3\1\0\4\3\1\115\33\3\21\0\2\3"+
    "\1\0\1\3\1\116\36\3\21\0\2\3\1\0\13\3"+
    "\1\117\24\3\21\0\2\3\1\0\16\3\1\120\21\3"+
    "\21\0\2\3\1\0\11\3\1\121\26\3\21\0\2\3"+
    "\1\0\2\3\1\122\35\3\21\0\2\3\1\0\27\3"+
    "\1\123\10\3\21\0\2\3\1\0\2\3\1\124\35\3"+
    "\21\0\2\3\1\0\27\3\1\125\10\3\21\0\2\3"+
    "\1\0\27\3\1\126\10\3\21\0\2\3\1\0\12\3"+
    "\1\127\25\3\21\0\2\3\1\0\3\3\1\130\34\3"+
    "\21\0\2\3\1\0\11\3\1\131\26\3\22\0\1\111"+
    "\60\0\1\132\1\0\2\3\1\0\2\3\1\133\35\3"+
    "\21\0\2\3\1\0\13\3\1\134\24\3\21\0\2\3"+
    "\1\0\2\3\1\135\35\3\21\0\2\3\1\0\36\3"+
    "\1\136\1\3\21\0\2\3\1\0\11\3\1\137\26\3"+
    "\21\0\2\3\1\0\1\3\1\140\36\3\21\0\2\3"+
    "\1\0\16\3\1\141\21\3\21\0\2\3\1\0\30\3"+
    "\1\142\7\3\21\0\2\3\1\0\2\3\1\143\35\3"+
    "\21\0\2\3\1\0\11\3\1\144\26\3\21\0\2\3"+
    "\1\0\2\3\1\145\35\3\21\0\2\3\1\0\12\3"+
    "\1\146\25\3\21\0\2\3\1\0\4\3\1\147\33\3"+
    "\21\0\2\3\1\0\21\3\1\150\16\3\21\0\2\3"+
    "\1\0\22\3\1\151\15\3\21\0\2\3\1\0\11\3"+
    "\1\152\26\3\21\0\2\3\1\0\16\3\1\153\21\3"+
    "\21\0\2\3\1\0\13\3\1\154\24\3\21\0\2\3"+
    "\1\0\24\3\1\155\13\3\21\0\2\3\1\0\3\3"+
    "\1\156\34\3\21\0\2\3\1\0\12\3\1\157\25\3"+
    "\21\0\2\3\1\0\4\3\1\160\33\3\21\0\2\3"+
    "\1\0\5\3\1\161\32\3\21\0\2\3\1\0\5\3"+
    "\1\162\32\3\21\0\2\3\1\0\11\3\1\163\26\3"+
    "\21\0\2\3\1\0\13\3\1\164\24\3\21\0\2\3"+
    "\1\0\13\3\1\165\24\3\21\0\2\3\1\0\16\3"+
    "\1\166\21\3\21\0\2\3\1\0\11\3\1\167\26\3"+
    "\21\0\2\3\1\0\1\3\1\170\36\3\21\0\2\3"+
    "\1\0\1\171\13\3\1\172\23\3\21\0\2\3\1\0"+
    "\6\3\1\173\31\3\21\0\2\3\1\0\36\3\1\174"+
    "\1\3\21\0\2\3\1\0\13\3\1\175\24\3\21\0"+
    "\2\3\1\0\7\3\1\176\30\3\21\0\2\3\1\0"+
    "\7\3\1\177\30\3\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4784];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\21\1\13\11\1\1\1\11\23\1\1\0"+
    "\24\1\1\0\20\1\1\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return ERROR;
            } 
            // fall through
          case 42: break;
          case 2: 
            { lexeme=yytext(); return Identificador;
            } 
            // fall through
          case 43: break;
          case 3: 
            { lexeme=yytext(); return Numero;
            } 
            // fall through
          case 44: break;
          case 4: 
            { /*Ignore*/
            } 
            // fall through
          case 45: break;
          case 5: 
            { lexeme=yytext(); return Division;
            } 
            // fall through
          case 46: break;
          case 6: 
            { lexeme=yytext(); return saltoLinea;
            } 
            // fall through
          case 47: break;
          case 7: 
            { lexeme=yytext(); return Igual;
            } 
            // fall through
          case 48: break;
          case 8: 
            { lexeme=yytext();return Menor;
            } 
            // fall through
          case 49: break;
          case 9: 
            { lexeme=yytext(); return Mayor;
            } 
            // fall through
          case 50: break;
          case 10: 
            { lexeme=yytext(); return Mas;
            } 
            // fall through
          case 51: break;
          case 11: 
            { lexeme=yytext(); return Resta;
            } 
            // fall through
          case 52: break;
          case 12: 
            { lexeme=yytext(); return Multiplicacion;
            } 
            // fall through
          case 53: break;
          case 13: 
            { lexeme=yytext(); return Potencia;
            } 
            // fall through
          case 54: break;
          case 14: 
            { lexeme=yytext(); return PuntoComa;
            } 
            // fall through
          case 55: break;
          case 15: 
            { lexeme=yytext(); return llaveApertura;
            } 
            // fall through
          case 56: break;
          case 16: 
            { lexeme=yytext(); return llaveCierre;
            } 
            // fall through
          case 57: break;
          case 17: 
            { lexeme=yytext(); return ParentesisApertura;
            } 
            // fall through
          case 58: break;
          case 18: 
            { lexeme=yytext(); return ParentesisCierre;
            } 
            // fall through
          case 59: break;
          case 19: 
            { lexeme=yytext(); return Ir;
            } 
            // fall through
          case 60: break;
          case 20: 
            { lexeme=yytext(); return Inc;
            } 
            // fall through
          case 61: break;
          case 21: 
            { lexeme=yytext(); return Dec;
            } 
            // fall through
          case 62: break;
          case 22: 
            { lexeme=yytext(); return Ent;
            } 
            // fall through
          case 63: break;
          case 23: 
            { lexeme=yytext(); return Car;
            } 
            // fall through
          case 64: break;
          case 24: 
            { lexeme=yytext(); return Alto;
            } 
            // fall through
          case 65: break;
          case 25: 
            { lexeme=yytext(); return Text;
            } 
            // fall through
          case 66: break;
          case 26: 
            { lexeme=yytext(); return Real;
            } 
            // fall through
          case 67: break;
          case 27: 
            { lexeme=yytext(); return Y_si;
            } 
            // fall through
          case 68: break;
          case 28: 
            { lexeme=yytext(); return Bool;
            } 
            // fall through
          case 69: break;
          case 29: 
            { lexeme=yytext(); return Tarea;
            } 
            // fall through
          case 70: break;
          case 30: 
            { lexeme=yytext(); return Avanza;
            } 
            // fall through
          case 71: break;
          case 31: 
            { lexeme=yytext(); return Repite;
            } 
            // fall through
          case 72: break;
          case 32: 
            { lexeme=yytext(); return Vibrar;
            } 
            // fall through
          case 73: break;
          case 33: 
            { lexeme=yytext(); return Ingresa;
            } 
            // fall through
          case 74: break;
          case 34: 
            { lexeme=yytext(); return Imprime;
            } 
            // fall through
          case 75: break;
          case 35: 
            { lexeme=yytext(); return Durante;
            } 
            // fall through
          case 76: break;
          case 36: 
            { lexeme=yytext(); return RealExt;
            } 
            // fall through
          case 77: break;
          case 37: 
            { lexeme=yytext(); return Publica;
            } 
            // fall through
          case 78: break;
          case 38: 
            { lexeme=yytext(); return Funcion;
            } 
            // fall through
          case 79: break;
          case 39: 
            { lexeme=yytext(); return Girar_Iz;
            } 
            // fall through
          case 80: break;
          case 40: 
            { lexeme=yytext(); return Girar_De;
            } 
            // fall through
          case 81: break;
          case 41: 
            { lexeme=yytext(); return Inicio_App;
            } 
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
