
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Inicio_App = 28;
  public static final int Llave_c = 23;
  public static final int Llave_a = 22;
  public static final int Detener = 43;
  public static final int Real = 33;
  public static final int VerificarBateria = 44;
  public static final int Advertencia = 10;
  public static final int operadorIncrementoDecremento = 5;
  public static final int operadorRelacional = 7;
  public static final int Corchete_c = 25;
  public static final int caracter = 11;
  public static final int Corchete_a = 24;
  public static final int Retroceder = 42;
  public static final int Gira_der = 40;
  public static final int Identificador_error = 12;
  public static final int Text = 30;
  public static final int Division = 19;
  public static final int Parentesis_c = 21;
  public static final int Parentesis_a = 20;
  public static final int Avanza = 41;
  public static final int EOF = 0;
  public static final int P_coma = 26;
  public static final int error = 1;
  public static final int Linea = 13;
  public static final int operadorBooleano = 4;
  public static final int punto = 32;
  public static final int ERROR = 27;
  public static final int Tarea = 36;
  public static final int numero_error = 35;
  public static final int Imprime = 8;
  public static final int Aviso = 9;
  public static final int Identificador = 2;
  public static final int Resta = 17;
  public static final int Mientras = 38;
  public static final int Bool = 34;
  public static final int operadorLogico = 6;
  public static final int Multiplicacion = 18;
  public static final int Ent = 29;
  public static final int Y_si = 37;
  public static final int Numero = 3;
  public static final int asignacion = 31;
  public static final int Suma = 16;
  public static final int Gira_izq = 39;
  public static final int Igual = 15;
  public static final int Comillas = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Numero",
  "operadorBooleano",
  "operadorIncrementoDecremento",
  "operadorLogico",
  "operadorRelacional",
  "Imprime",
  "Aviso",
  "Advertencia",
  "caracter",
  "Identificador_error",
  "Linea",
  "Comillas",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "P_coma",
  "ERROR",
  "Inicio_App",
  "Ent",
  "Text",
  "asignacion",
  "punto",
  "Real",
  "Bool",
  "numero_error",
  "Tarea",
  "Y_si",
  "Mientras",
  "Gira_izq",
  "Gira_der",
  "Avanza",
  "Retroceder",
  "Detener",
  "VerificarBateria"
  };
}

