
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 02 18:05:27 MDT 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Numero = 16;
  public static final int Mas = 8;
  public static final int ERROR = 17;
  public static final int Identificador = 15;
  public static final int saltoLinea = 6;
  public static final int EOF = 0;
  public static final int llaveCierre = 14;
  public static final int Division = 11;
  public static final int Resta = 9;
  public static final int Y_si = 2;
  public static final int error = 1;
  public static final int Bool = 5;
  public static final int Text = 3;
  public static final int Igual = 7;
  public static final int Multiplicacion = 10;
  public static final int llaveApertura = 13;
  public static final int PuntoComa = 12;
  public static final int Inicio_App = 4;
}

